In [1]:
import numpy as np
import pandas as pd

In [2]:
data_one = {"A": ["A0", "A1", "A2", "A3"], "B": ["B0", "B1", "B2", "B3"]}

In [3]:
data_two = {"C": ["C0", "C1", "C2", "C3"], "D": ["D0", "D1", "D2", "D3"]}

In [4]:
one = pd.DataFrame(data_one)

In [5]:
two = pd.DataFrame(data_two)

In [6]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [7]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [8]:
pd.concat([one,two], axis=1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [9]:
pd.concat([one,two], axis=0)

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [10]:
two.columns = one.columns

In [11]:
two

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [13]:
mydf = pd.concat([one,two], axis=0)

In [14]:
mydf.reset_index()

   index   A   B
0      0  A0  B0
1      1  A1  B1
2      2  A2  B2
3      3  A3  B3
4      0  C0  D0
5      1  C1  D1
6      2  C2  D2
7      3  C3  D3