In [1]:
import numpy as np
import pandas as pd

In [2]:
registrations = pd.DataFrame({"reg_id": [1,2,3,4], "name": ["Andrew", "Bob", "Charlie", "David"]})
logins = pd.DataFrame({"log_id": [1,2,3,4], "name": ["Xavier", "Andrew", "Yolanda", "Bob"]})

In [3]:
registrations

   reg_id     name
0       1   Andrew
1       2      Bob
2       3  Charlie
3       4    David

In [4]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4      Bob

In [5]:
pd.merge(registrations, logins, how="inner", on="name")

   reg_id    name  log_id
0       1  Andrew       2
1       2     Bob       4